"""initial_schema

Revision ID: 3f1fade8e943
Revises: 
Create Date: 2026-07-23 11:34:38.678172

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f1fade8e943'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('projects',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name', name='uq_projects_name')
    )
    op.create_index('ix_projects_name', 'projects', ['name'], unique=False)
    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'key', name='uq_application_settings_project_key')
    )
    op.create_index('ix_application_settings_key', 'application_settings', ['key'], unique=False)
    op.create_table('assets',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('asset_type', sa.String(length=255), nullable=True),
    sa.Column('zone', sa.String(length=255), nullable=True),
    sa.Column('vendor', sa.String(length=255), nullable=True),
    sa.Column('firmware_version', sa.String(length=255), nullable=True),
    sa.Column('exposure_level', sa.String(length=255), nullable=True),
    sa.Column('patch_level', sa.String(length=255), nullable=True),
    sa.Column('criticality', sa.String(length=255), nullable=True),
    sa.Column('availability_requirement', sa.String(length=255), nullable=True),
    sa.Column('integrity_requirement', sa.String(length=255), nullable=True),
    sa.Column('confidentiality_requirement', sa.String(length=255), nullable=True),
    sa.Column('intrinsic_probability', sa.Float(), nullable=True),
    sa.Column('x_position', sa.Float(), nullable=True),
    sa.Column('y_position', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'asset_name', name='uq_assets_project_asset')
    )
    op.create_index('ix_assets_asset_name', 'assets', ['asset_name'], unique=False)
    op.create_index('ix_assets_project_id', 'assets', ['project_id'], unique=False)
    op.create_table('bayesian_nodes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('node_type', sa.String(length=255), nullable=True),
    sa.Column('metadata', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'node_name', name='uq_bayesian_nodes_project_name')
    )
    op.create_index('ix_bayesian_nodes_project_id', 'bayesian_nodes', ['project_id'], unique=False)
    op.create_table('connections',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_asset', sa.String(length=255), nullable=False),
    sa.Column('destination_asset', sa.String(length=255), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=True),
    sa.Column('propagation_weight', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'source_asset', 'destination_asset', name='uq_connections_project_edge')
    )
    op.create_index('ix_connections_project_id', 'connections', ['project_id'], unique=False)
    op.create_table('cpts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('node_name', sa.String(length=255), nullable=False),
    sa.Column('table_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'node_name', name='uq_cpts_project_node')
    )
    op.create_index('ix_cpts_project_id', 'cpts', ['project_id'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('path', sa.Text(), nullable=True),
    sa.Column('report_type', sa.String(length=255), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'filename', name='uq_reports_project_filename')
    )
    op.create_index('ix_reports_project_id', 'reports', ['project_id'], unique=False)
    op.create_table('inference_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('posterior_probability', sa.Float(), nullable=False),
    sa.Column('inference_timestamp', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_inference_results_asset_id', 'inference_results', ['asset_id'], unique=False)
    op.create_index('ix_inference_results_project_id', 'inference_results', ['project_id'], unique=False)
    op.create_table('risk_results',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.Column('asset_name', sa.String(length=255), nullable=False),
    sa.Column('likelihood', sa.Float(), nullable=True),
    sa.Column('impact', sa.Float(), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=True),
    sa.Column('risk_level', sa.String(length=255), nullable=True),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_risk_results_asset_id', 'risk_results', ['asset_id'], unique=False)
    op.create_index('ix_risk_results_project_id', 'risk_results', ['project_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_risk_results_project_id', table_name='risk_results')
    op.drop_index('ix_risk_results_asset_id', table_name='risk_results')
    op.drop_table('risk_results')
    op.drop_index('ix_inference_results_project_id', table_name='inference_results')
    op.drop_index('ix_inference_results_asset_id', table_name='inference_results')
    op.drop_table('inference_results')
    op.drop_index('ix_reports_project_id', table_name='reports')
    op.drop_table('reports')
    op.drop_index('ix_cpts_project_id', table_name='cpts')
    op.drop_table('cpts')
    op.drop_index('ix_connections_project_id', table_name='connections')
    op.drop_table('connections')
    op.drop_index('ix_bayesian_nodes_project_id', table_name='bayesian_nodes')
    op.drop_table('bayesian_nodes')
    op.drop_index('ix_assets_project_id', table_name='assets')
    op.drop_index('ix_assets_asset_name', table_name='assets')
    op.drop_table('assets')
    op.drop_index('ix_application_settings_key', table_name='application_settings')
    op.drop_table('application_settings')
    op.drop_index('ix_projects_name', table_name='projects')
    op.drop_table('projects')
    # ### end Alembic commands ###
